### PR TITLE
add display to errors

### PR DESCRIPTION
**Pull request by peepopoggers**

### CODE REVIEW

**Comment by wassup-** [comment]
Thanks for the PR!

**Comment by peepopoggers** [comment]
@wassup- err.. i am stupid and did not test this :skull: reverse this pr because for some reason display will not work/ compile :0

**Comment by wassup-** [comment]
Hmm, I am currently not at my computer :/ I will undo the changes later tonight.

Did you take a look at the contributing guide? We should always make sure the project builds and all tests pass before creating a PR. I'm also to blame because I did not test these changes myself before merging the PR.

**Comment by peepopoggers** [comment]
I am more to blame :sob: I have been overly lazy with everything for a couple months. Next PR will be tested ten times over :cat: :+1:

**Pull request merged**
